web/router.ex
defmodule ChatApp.Router do
  use ChatApp.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChatApp do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/chat_rooms", ChatRoomController do
      post "/messages", ChatRoomController, :create_message, as: :create_message
    end
  end

  scope "/api", ChatApp do
    pipe_through :api

    scope "/v1", V1, as: :v1 do
      resources "/chat_rooms", ChatRoomController, except: [:new, :edit] do
        get "/messages", ChatRoomController, :index_message, as: :index_message
        post "/messages", ChatRoomController, :create_message, as: :create_message
        delete "/messages/:id", ChatRoomController, :delete_message, as: :delete_message
      end
    end
  end
end

lib/chat_app/endpoint.ex
defmodule ChatApp.Endpoint do
  use Phoenix.Endpoint, otp_app: :chat_app

  socket "/socket", ChatApp.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :chat_app, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_chat_app_key",
    signing_salt: "CzAk3pks"

  plug ChatApp.Router
end

lib/chat_app/repo.ex
defmodule ChatApp.Repo do
  use Ecto.Repo, otp_app: :chat_app
end

web/models/chat_room.ex
defmodule ChatApp.ChatRoom do
  use ChatApp.Web, :model

  schema "chat_rooms" do
    field :name, :string

    has_many :messages, ChatApp.Message
    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name])
    |> validate_required([:name])
  end
end

web/models/message.ex
defmodule ChatApp.Message do
  use ChatApp.Web, :model

  import Ecto.Query, only: [from: 2]

  alias ChatApp.Repo

  schema "messages" do
    field :content, :string
    belongs_to :chat_room, ChatApp.ChatRoom

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:content, :chat_room_id])
    |> validate_required([:content, :chat_room_id])
  end

  def otl(query) do
    from m in query, order_by: [asc: m.inserted_at]
  end
end

web/controllers/chat_room_controller.ex
defmodule ChatApp.ChatRoomController do
  use ChatApp.Web, :controller

  alias ChatApp.ChatRoom
  alias ChatApp.Message

  plug :scrub_params, "message" when action in [:create_message]

  def index(conn, _params) do
    chat_rooms = Repo.all(ChatRoom)
    render(conn, "index.html", chat_rooms: chat_rooms)
  end

  def new(conn, _params) do
    changeset = ChatRoom.changeset(%ChatRoom{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"chat_room" => chat_room_params}) do
    changeset = ChatRoom.changeset(%ChatRoom{}, chat_room_params)

    case Repo.insert(changeset) do
      {:ok, _chat_room} ->
        conn
        |> put_flash(:info, "Chat room created successfully.")
        |> redirect(to: chat_room_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    chat_room = Repo.get!(ChatRoom, id)
                |> Repo.preload(messages: Message.otl(Message))
    changeset = Message.changeset(%Message{})

    render(conn, "show.html", chat_room: chat_room,
                              messages: chat_room.messages,
                              changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    chat_room = Repo.get!(ChatRoom, id)
    changeset = ChatRoom.changeset(chat_room)
    render(conn, "edit.html", chat_room: chat_room, changeset: changeset)
  end

  def update(conn, %{"id" => id, "chat_room" => chat_room_params}) do
    chat_room = Repo.get!(ChatRoom, id)
    changeset = ChatRoom.changeset(chat_room, chat_room_params)

    case Repo.update(changeset) do
      {:ok, chat_room} ->
        conn
        |> put_flash(:info, "Chat room updated successfully.")
        |> redirect(to: chat_room_path(conn, :show, chat_room))
      {:error, changeset} ->
        render(conn, "edit.html", chat_room: chat_room, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    chat_room = Repo.get!(ChatRoom, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(chat_room)

    conn
    |> put_flash(:info, "Chat room deleted successfully.")
    |> redirect(to: chat_room_path(conn, :index))
  end

  def create_message(conn, %{"message" => message_params, "chat_room_id" => chat_room_id}) do
    changeset = Message.changeset(%Message{}, Map.put(message_params, "chat_room_id", chat_room_id))
    chat_room = Repo.get!(ChatRoom, chat_room_id)
                |> Repo.preload(messages: Message.otl(Message))

    case Repo.insert(changeset) do
      {:ok, _message} ->
        conn
        |> redirect(to: chat_room_path(conn, :show, chat_room))
      {:error, changeset} ->
        render(conn, "show.html", chat_room: chat_room,
                                  messages: chat_room.messages,
                                  changeset: changeset)
    end
  end
end

web/controllers/page_controller.ex
defmodule ChatApp.PageController do
  use ChatApp.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/v1/chat_room_controller.ex
defmodule ChatApp.V1.ChatRoomController do
  use ChatApp.Web, :controller

  import Ecto.Query, only: [where: 2]

  alias ChatApp.ChatRoom
  alias ChatApp.Message

  def index_message(conn, %{"chat_room_id" => chat_room_id}) do
    messages = Message
               |> where(chat_room_id: ^chat_room_id)
               |> Message.otl
               |> Repo.all

    render conn, ChatApp.V1.MessageView, "index.json", messages: messages
  end

  def create_message(conn, %{"content" => content, "chat_room_id" => chat_room_id}) do
    changeset = Message.changeset(%Message{}, %{content: content, chat_room_id: chat_room_id})

    case Repo.insert(changeset) do
      {:ok, message} ->
        conn
        |> render(ChatApp.V1.MessageView, "message.json", message: message)
    end
  end

  def delete_message(conn, %{"id" => id}) do
    message = Repo.get!(Message, id)

    Repo.delete!(message)

    conn
    |> json(%{})
  end
end

web/views/chat_room_view.ex
defmodule ChatApp.ChatRoomView do
  use ChatApp.Web, :view
end

web/views/error_view.ex
defmodule ChatApp.ErrorView do
  use ChatApp.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule ChatApp.LayoutView do
  use ChatApp.Web, :view
end

web/views/page_view.ex
defmodule ChatApp.PageView do
  use ChatApp.Web, :view
end

web/views/shared_view.ex
defmodule ChatApp.SharedView do
  use ChatApp.Web, :view
end

web/views/v1/message_view.ex
defmodule ChatApp.V1.MessageView do
  use ChatApp.Web, :view

  def render("index.json", %{messages: messages}) do
    %{data: render_many(messages, ChatApp.V1.MessageView, "message.json")}
  end

  def render("message.json", %{message: message}) do
    %{id: message.id,
      content: message.content,
      created_at: message.inserted_at}
  end
end

web/templates/chat_room/edit.html.eex
<%= render ChatApp.SharedView, "title.html", title: "Edit chat room" %>

<%= render "form.html", changeset: @changeset,
                        back_to: chat_room_path(@conn, :index),
                        action: chat_room_path(@conn, :update, @chat_room) %>

web/templates/chat_room/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="field">
    <%= label f, :name, class: "label" %>
    <p class="control">
      <%= text_input f, :name, class: "input" %>
    </p>
    <%= error_tag f, :name %>
  </div>

  <div class="field is-grouped">
    <p class="control">
      <%= submit "Submit", class: "button is-primary" %>
    </p>
    <p class="control">
      <%= link "Back", to: @back_to, class: "button is-link" %>
    </p>
  </div>
<% end %>

web/templates/chat_room/index.html.eex
<%= render ChatApp.SharedView, "title.html", title: "Listing chat rooms" %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for chat_room <- @chat_rooms do %>
    <tr>
      <td><%= chat_room.name %></td>

      <td>
        <div class="field is-grouped is-pulled-right">
          <p class="control">
            <%= link "Show", to: chat_room_path(@conn, :show, chat_room), class: "button" %>
          </p>
          <p class="control">
            <%= link "Edit", to: chat_room_path(@conn, :edit, chat_room), class: "button" %>
          </p>
          <%= link "Delete", to: chat_room_path(@conn, :delete, chat_room), method: :delete, data: [confirm: "Are you sure?"], class: "button is-danger" %>
        </div>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New chat room", to: chat_room_path(@conn, :new), class: "button" %>

web/templates/chat_room/new.html.eex
<%= render ChatApp.SharedView, "title.html", title: "New chat room" %>

<%= render "form.html", changeset: @changeset,
                        back_to: chat_room_path(@conn, :index),
                        action: chat_room_path(@conn, :create) %>

web/templates/chat_room/show.html.eex
<%= render ChatApp.SharedView, "title.html", title: @chat_room.name %>

<ul>
<%= for message <- @messages do %>
  <li><%= message.content %></li>
<% end %>
</ul>

<%= form_for @changeset, chat_room_create_message_path(@conn, :create_message, @chat_room), fn f -> %>
<div class="field has-addons">
  <p class="control is-expanded">
    <%= text_input f, :content, class: "input" %>
  </p>
  <p class="control">
    <%= submit "Send", class: "button is-primary" %>
  </p>
</div>

<div class="field is-grouped">
  <p class="control">
    <%= link "Edit", to: chat_room_path(@conn, :edit, @chat_room), class: "button is-info" %>
  </p>
  <p class="control">
    <%= link "Back", to: chat_room_path(@conn, :index), class: "button is-link" %>
  </p>
</div>
<% end %>

web/templates/layout/_alerts.html.eex
<%= if info = get_flash(@conn, :info) do %>
  <div class="notification is-info" role="alert"><%= info %></div>
<% end %>

<%= if error = get_flash(@conn, :error) do %>
  <div class="notification is-danger" role="alert"><%= error %></div>
<% end %>

web/templates/layout/_header.html.eex
<header class="header">
  <nav class="nav" role="navigation">
    <div class="nav-left">
      <a class="nav-item">
        <img src="<%= static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix's logo">
      </a>
    </div>

    <div class="nav-right">
      <%= link("Chat Rooms", to: chat_room_path(@conn, :index), class: "nav-item") %>
    </div>
  </nav>
</header>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello ChatApp!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <%= render "_header.html", assigns %>

      <%= render "_alerts.html", assigns %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<section class="hero is-primary is-medium">
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        Chat App
      </h1>
      <h2 class="subtitle">
        build with Phoenix
      </h2>
    </div>
  </div>
</section>

web/templates/shared/title.html.eex
<h1 class="title has-text-centered"><%= @title %></h1>